name = "ModularFormsModuloTwo"
uuid = "1d2b6a6e-f79c-4b33-849e-5348bdb84a0f"
version = "1.0.0"
author = ["pauldubois98@hotmail.com"]



[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"
FileIO = "1.2"
JLD2 = "0.1"
PrettyTables = "0.8.3"
Primes = "0.4"
